name: 'Action Pulsar Dependency Tester'
description: 'Test changes in Core Dependencies of Pulsar'
author: confused-Techie
branding:
  icon: check-square
  color: purple
runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt install -y libnotify4
        curl -L "https://download.pulsar-edit.dev/?os=linux&type=linux_deb" --output pulsar.deb
        sudo dpkg -i pulsar.deb
    - if: runner.os == 'macOS'
      shell: bash
      run: |
        curl -L "https://download.pulsar-edit.dev/?os=intel_mac&type=mac_dmg" --output pulsar.dmg
        hdiutil attach pulsar.dmg
        sudo cp -rf /Volumes/Pulsar*/Pulsar.app /Applications
        xattr -cr /Applications/Pulsar.app/
        sudo ln -s /Applications/Pulsar.app/Contents/MacOS/Pulsar /usr/local/bin/pulsar
    - if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $wc = New-Object System.Net.WebClient
        $url = "https://download.pulsar-edit.dev/?os=windows&type=windows_setup"
        $downloadPath = "pulsarInstall.exe"

        Write-Host "Downloading Pulsar to $downloadPath"
        $wc.DownloadFile($url, $downloadPath)

        Write-Host "Installing Pulsar - this may take awhile"
        Start-Process -FilePath $downloadPath
        Write-Host "Pulsar Install completed"

        $Env:PATH += ";$env:LOCALAPPDATA\Programs\Pulsar"

        # Invoke-WebRequest -URI "https://download.pulsar-edit.dev/?os=windows&type=windows_portable" -OutFile "$env:LOCALAPPDATA\Microsoft\WindowsApps\pulsar.exe"
