name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pulsar Editor
        uses: ./
      - if: runner.os == 'Windows'
        run: |
          $env:Path = (@(
            [System.Environment]::GetEnvironmentVariable("Path","Machine"),
            [System.Environment]::GetEnvironmentVariable("Path","User")
          ) -join ';')
          pulsar -v
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        run: pulsar -v
      
        
        
