name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pulsar Editor
        uses: ./
      - if: runner.os == 'Windows'
        run: |
          [System.Environment]::GetEnvironmentVariable("Path","Machine")
          Get-ChildItem -Path ([System.Environment]::GetEnvironmentVariable("ProgramFiles"))
          Get-ChildItem -Path ([System.Environment]::GetEnvironmentVariable("ProgramFiles(x86)"))
          Get-ChildItem -Path ([System.Environment]::GetEnvironmentVariable("LOCALAPPDATA"))
          if (Test-Path "$($env:LOCALAPPDATA)\Programs") { Get-ChildItem -Path "$([System.Environment]::GetEnvironmentVariable("LOCALAPPDATA"))\Programs" }
      - run: pulsar -v
      
        
        
